### ISSUE TITLE
动态添加路由失败

### ISSUE THREAD

**Issue by HenryZhouHB** [zhoutaoo/SpringCloud#72]
**BUG描述**
动态添加路由后，数据表中并没有新添加的路由
点击Refresh Routes Cache，显示如下错误
 Fetching gateway routes failed.
Request failed with status code 500 

**截图**
![image](https://user-images.githubusercontent.com/52985827/63988817-90c11900-cb10-11e9-8cd5-dc18e977c7b8.png)

**环境**

操作系统、组件版本、数据库等

**Comment by zhoutaoo** [comment]
请贴错误信息

**Comment by HenryZhouHB** [comment]
2019-09-04 10:14:53.085 ERROR [gateway-web,05719355369d7c9e,05719355369d7c9e,false] 1 --- [reactor-http-epoll-3] c.s.c.g.e.GateWayExceptionHandlerAdvice  : runtime exception:The parameter [www.baidu.com] format is incorrect, scheme can not be empty
2019-09-04 10:14:53.089 ERROR [gateway-web,05719355369d7c9e,05719355369d7c9e,false] 1 --- [reactor-http-epoll-3] a.w.r.e.AbstractErrorWebExceptionHandler : [08ee7879] 500 Server Error for HTTP GET "/actuator/gateway/routes"
java.lang.IllegalArgumentException: The parameter [www.baidu.com] format is incorrect, scheme can not be empty
	at org.springframework.util.Assert.hasText(Assert.java:284) ~[spring-core-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.cloud.gateway.route.Route$AbstractBuilder.uri(Route.java:118) ~[spring-cloud-gateway-core-2.1.0.RELEASE.jar!/:2.1.0.RELEASE]

**Comment by zhoutaoo** [comment]
The parameter [www.baidu.com] format is incorrect, scheme can not be empty
scheme不能为空

**Comment by HenryZhouHB** [comment]
怎么删掉这条路由啊

**Comment by HenryZhouHB** [comment]
没有看到删路由的入口

**Comment by zhoutaoo** [comment]
http://localhost:8445/gateway/routes/${id}
可以看swagger的文档
